#############################################################################
# Makefile for building: ElevatorSimulator
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  ElevatorSimulator.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ElevatorSimulator.pro -spec linux-g++ CONFIG+=debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ElevatorSimulator1.0.0
DISTDIR = /home/student/Documents/a3/ElevatorSimulator/.tmp/ElevatorSimulator1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = BuildingSetting.cpp \
		CloseButton.cpp \
		Display.cpp \
		Door.cpp \
		Elevator.cpp \
		ElevatorSetting.cpp \
		Floor.cpp \
		FloorButton.cpp \
		HelpButton.cpp \
		MainWindow.cpp \
		OpenButton.cpp \
		Passenger.cpp \
		PassengerSetting.cpp \
		Simulation.cpp \
		Speaker.cpp \
		main.cpp \
		ElevatorControl.cpp \
		NCStrategy.cpp \
		FloorRequest.cpp \
		SimulationManager.cpp moc_CloseButton.cpp \
		moc_Display.cpp \
		moc_Door.cpp \
		moc_Elevator.cpp \
		moc_ElevatorSetting.cpp \
		moc_Floor.cpp \
		moc_FloorButton.cpp \
		moc_HelpButton.cpp \
		moc_MainWindow.cpp \
		moc_OpenButton.cpp \
		moc_Passenger.cpp \
		moc_PassengerSetting.cpp \
		moc_Simulation.cpp \
		moc_SimulationComponent.cpp \
		moc_Button.cpp \
		moc_Speaker.cpp
OBJECTS       = BuildingSetting.o \
		CloseButton.o \
		Display.o \
		Door.o \
		Elevator.o \
		ElevatorSetting.o \
		Floor.o \
		FloorButton.o \
		HelpButton.o \
		MainWindow.o \
		OpenButton.o \
		Passenger.o \
		PassengerSetting.o \
		Simulation.o \
		Speaker.o \
		main.o \
		ElevatorControl.o \
		NCStrategy.o \
		FloorRequest.o \
		SimulationManager.o \
		moc_CloseButton.o \
		moc_Display.o \
		moc_Door.o \
		moc_Elevator.o \
		moc_ElevatorSetting.o \
		moc_Floor.o \
		moc_FloorButton.o \
		moc_HelpButton.o \
		moc_MainWindow.o \
		moc_OpenButton.o \
		moc_Passenger.o \
		moc_PassengerSetting.o \
		moc_Simulation.o \
		moc_SimulationComponent.o \
		moc_Button.o \
		moc_Speaker.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ElevatorSimulator.pro BuildingSetting.h \
		CloseButton.h \
		Display.h \
		Door.h \
		Elevator.h \
		ElevatorSetting.h \
		Floor.h \
		FloorButton.h \
		HelpButton.h \
		MainWindow.h \
		ElevatorState.h \
		Direction.h \
		DoorState.h \
		OpenButton.h \
		Passenger.h \
		PassengerState.h \
		PassengerSetting.h \
		Simulation.h \
		SimulationComponent.h \
		Button.h \
		Speaker.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		NCStrategy.h \
		FloorRequest.h \
		SimulationManager.h \
		Random.h BuildingSetting.cpp \
		CloseButton.cpp \
		Display.cpp \
		Door.cpp \
		Elevator.cpp \
		ElevatorSetting.cpp \
		Floor.cpp \
		FloorButton.cpp \
		HelpButton.cpp \
		MainWindow.cpp \
		OpenButton.cpp \
		Passenger.cpp \
		PassengerSetting.cpp \
		Simulation.cpp \
		Speaker.cpp \
		main.cpp \
		ElevatorControl.cpp \
		NCStrategy.cpp \
		FloorRequest.cpp \
		SimulationManager.cpp
QMAKE_TARGET  = ElevatorSimulator
DESTDIR       = 
TARGET        = ElevatorSimulator


first: all
####### Build rules

ElevatorSimulator: ui_CloseButton.h ui_Display.h ui_Door.h ui_Elevator.h ui_ElevatorSetting.h ui_Floor.h ui_FloorButton.h ui_HelpButton.h ui_MainWindow.h ui_OpenButton.h ui_Passenger.h ui_PassengerSetting.h ui_Simulation.h ui_Speaker.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ElevatorSimulator.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ElevatorSimulator.pro
	$(QMAKE) -o Makefile ElevatorSimulator.pro -spec linux-g++ CONFIG+=debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
ElevatorSimulator.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ElevatorSimulator.pro -spec linux-g++ CONFIG+=debug

qmake_all: FORCE


all: Makefile ElevatorSimulator

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents BuildingSetting.h CloseButton.h Display.h Door.h Elevator.h ElevatorSetting.h Floor.h FloorButton.h HelpButton.h MainWindow.h ElevatorState.h Direction.h DoorState.h OpenButton.h Passenger.h PassengerState.h PassengerSetting.h Simulation.h SimulationComponent.h Button.h Speaker.h ElevatorControl.h AllocationStrategy.h NCStrategy.h FloorRequest.h SimulationManager.h Random.h $(DISTDIR)/
	$(COPY_FILE) --parents BuildingSetting.cpp CloseButton.cpp Display.cpp Door.cpp Elevator.cpp ElevatorSetting.cpp Floor.cpp FloorButton.cpp HelpButton.cpp MainWindow.cpp OpenButton.cpp Passenger.cpp PassengerSetting.cpp Simulation.cpp Speaker.cpp main.cpp ElevatorControl.cpp NCStrategy.cpp FloorRequest.cpp SimulationManager.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CloseButton.ui Display.ui Door.ui Elevator.ui ElevatorSetting.ui Floor.ui FloorButton.ui HelpButton.ui MainWindow.ui OpenButton.ui Passenger.ui PassengerSetting.ui Simulation.ui Speaker.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_CloseButton.cpp moc_Display.cpp moc_Door.cpp moc_Elevator.cpp moc_ElevatorSetting.cpp moc_Floor.cpp moc_FloorButton.cpp moc_HelpButton.cpp moc_MainWindow.cpp moc_OpenButton.cpp moc_Passenger.cpp moc_PassengerSetting.cpp moc_Simulation.cpp moc_SimulationComponent.cpp moc_Button.cpp moc_Speaker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_CloseButton.cpp moc_Display.cpp moc_Door.cpp moc_Elevator.cpp moc_ElevatorSetting.cpp moc_Floor.cpp moc_FloorButton.cpp moc_HelpButton.cpp moc_MainWindow.cpp moc_OpenButton.cpp moc_Passenger.cpp moc_PassengerSetting.cpp moc_Simulation.cpp moc_SimulationComponent.cpp moc_Button.cpp moc_Speaker.cpp
moc_CloseButton.cpp: CloseButton.h \
		Button.h \
		SimulationComponent.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		Display.h \
		Speaker.h \
		Direction.h \
		OpenButton.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include CloseButton.h -o moc_CloseButton.cpp

moc_Display.cpp: Display.h \
		SimulationComponent.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Display.h -o moc_Display.cpp

moc_Door.cpp: Door.h \
		DoorState.h \
		SimulationComponent.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Door.h -o moc_Door.cpp

moc_Elevator.cpp: Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		SimulationComponent.h \
		Display.h \
		Speaker.h \
		Direction.h \
		OpenButton.h \
		Button.h \
		Elevator.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Elevator.h -o moc_Elevator.cpp

moc_ElevatorSetting.cpp: ElevatorSetting.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ElevatorSetting.h -o moc_ElevatorSetting.cpp

moc_Floor.cpp: Floor.h \
		SimulationComponent.h \
		Direction.h \
		FloorButton.h \
		Button.h \
		Floor.h \
		ElevatorControl.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		Display.h \
		Speaker.h \
		OpenButton.h \
		CloseButton.h \
		HelpButton.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Floor.h -o moc_Floor.cpp

moc_FloorButton.cpp: FloorButton.h \
		Button.h \
		SimulationComponent.h \
		Direction.h \
		Floor.h \
		FloorButton.h \
		ElevatorControl.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		Display.h \
		Speaker.h \
		OpenButton.h \
		CloseButton.h \
		HelpButton.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include FloorButton.h -o moc_FloorButton.cpp

moc_HelpButton.cpp: HelpButton.h \
		Button.h \
		SimulationComponent.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		Display.h \
		Speaker.h \
		Direction.h \
		OpenButton.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include HelpButton.h -o moc_HelpButton.cpp

moc_MainWindow.cpp: MainWindow.h \
		ElevatorSetting.h \
		PassengerSetting.h \
		Direction.h \
		BuildingSetting.h \
		Simulation.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		SimulationComponent.h \
		Display.h \
		Speaker.h \
		OpenButton.h \
		Button.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		Passenger.h \
		PassengerState.h \
		Floor.h \
		FloorButton.h \
		SimulationManager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MainWindow.h -o moc_MainWindow.cpp

moc_OpenButton.cpp: OpenButton.h \
		Button.h \
		SimulationComponent.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		Display.h \
		Speaker.h \
		Direction.h \
		OpenButton.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include OpenButton.h -o moc_OpenButton.cpp

moc_Passenger.cpp: Passenger.h \
		SimulationComponent.h \
		PassengerState.h \
		Button.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Passenger.h -o moc_Passenger.cpp

moc_PassengerSetting.cpp: PassengerSetting.h \
		Direction.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include PassengerSetting.h -o moc_PassengerSetting.cpp

moc_Simulation.cpp: Simulation.h \
		ElevatorSetting.h \
		PassengerSetting.h \
		Direction.h \
		BuildingSetting.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		SimulationComponent.h \
		Display.h \
		Speaker.h \
		OpenButton.h \
		Button.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		Passenger.h \
		PassengerState.h \
		Floor.h \
		FloorButton.h \
		SimulationManager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Simulation.h -o moc_Simulation.cpp

moc_SimulationComponent.cpp: SimulationComponent.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include SimulationComponent.h -o moc_SimulationComponent.cpp

moc_Button.cpp: Button.h \
		SimulationComponent.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Button.h -o moc_Button.cpp

moc_Speaker.cpp: Speaker.h \
		SimulationComponent.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/student/Documents/a3/ElevatorSimulator/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/Documents/a3/ElevatorSimulator -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Speaker.h -o moc_Speaker.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_CloseButton.h ui_Display.h ui_Door.h ui_Elevator.h ui_ElevatorSetting.h ui_Floor.h ui_FloorButton.h ui_HelpButton.h ui_MainWindow.h ui_OpenButton.h ui_Passenger.h ui_PassengerSetting.h ui_Simulation.h ui_Speaker.h
compiler_uic_clean:
	-$(DEL_FILE) ui_CloseButton.h ui_Display.h ui_Door.h ui_Elevator.h ui_ElevatorSetting.h ui_Floor.h ui_FloorButton.h ui_HelpButton.h ui_MainWindow.h ui_OpenButton.h ui_Passenger.h ui_PassengerSetting.h ui_Simulation.h ui_Speaker.h
ui_CloseButton.h: CloseButton.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic CloseButton.ui -o ui_CloseButton.h

ui_Display.h: Display.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Display.ui -o ui_Display.h

ui_Door.h: Door.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Door.ui -o ui_Door.h

ui_Elevator.h: Elevator.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Elevator.ui -o ui_Elevator.h

ui_ElevatorSetting.h: ElevatorSetting.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ElevatorSetting.ui -o ui_ElevatorSetting.h

ui_Floor.h: Floor.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Floor.ui -o ui_Floor.h

ui_FloorButton.h: FloorButton.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic FloorButton.ui -o ui_FloorButton.h

ui_HelpButton.h: HelpButton.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic HelpButton.ui -o ui_HelpButton.h

ui_MainWindow.h: MainWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic MainWindow.ui -o ui_MainWindow.h

ui_OpenButton.h: OpenButton.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic OpenButton.ui -o ui_OpenButton.h

ui_Passenger.h: Passenger.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Passenger.ui -o ui_Passenger.h

ui_PassengerSetting.h: PassengerSetting.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic PassengerSetting.ui -o ui_PassengerSetting.h

ui_Simulation.h: Simulation.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Simulation.ui -o ui_Simulation.h

ui_Speaker.h: Speaker.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic Speaker.ui -o ui_Speaker.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

BuildingSetting.o: BuildingSetting.cpp BuildingSetting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BuildingSetting.o BuildingSetting.cpp

CloseButton.o: CloseButton.cpp CloseButton.h \
		Button.h \
		SimulationComponent.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		Display.h \
		Speaker.h \
		Direction.h \
		OpenButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		ui_CloseButton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CloseButton.o CloseButton.cpp

Display.o: Display.cpp Display.h \
		SimulationComponent.h \
		ui_Display.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Display.o Display.cpp

Door.o: Door.cpp Door.h \
		DoorState.h \
		SimulationComponent.h \
		ui_Door.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Door.o Door.cpp

Elevator.o: Elevator.cpp Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		SimulationComponent.h \
		Display.h \
		Speaker.h \
		Direction.h \
		OpenButton.h \
		Button.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		ui_Elevator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Elevator.o Elevator.cpp

ElevatorSetting.o: ElevatorSetting.cpp ElevatorSetting.h \
		ui_ElevatorSetting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ElevatorSetting.o ElevatorSetting.cpp

Floor.o: Floor.cpp Floor.h \
		SimulationComponent.h \
		Direction.h \
		FloorButton.h \
		Button.h \
		ElevatorControl.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		Display.h \
		Speaker.h \
		OpenButton.h \
		CloseButton.h \
		HelpButton.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		ui_Floor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Floor.o Floor.cpp

FloorButton.o: FloorButton.cpp FloorButton.h \
		Button.h \
		SimulationComponent.h \
		Direction.h \
		Floor.h \
		ElevatorControl.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		Display.h \
		Speaker.h \
		OpenButton.h \
		CloseButton.h \
		HelpButton.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		ui_FloorButton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FloorButton.o FloorButton.cpp

HelpButton.o: HelpButton.cpp HelpButton.h \
		Button.h \
		SimulationComponent.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		Display.h \
		Speaker.h \
		Direction.h \
		OpenButton.h \
		CloseButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		ui_HelpButton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HelpButton.o HelpButton.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		ElevatorSetting.h \
		PassengerSetting.h \
		Direction.h \
		BuildingSetting.h \
		Simulation.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		SimulationComponent.h \
		Display.h \
		Speaker.h \
		OpenButton.h \
		Button.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		Passenger.h \
		PassengerState.h \
		Floor.h \
		FloorButton.h \
		SimulationManager.h \
		ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

OpenButton.o: OpenButton.cpp OpenButton.h \
		Button.h \
		SimulationComponent.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		Display.h \
		Speaker.h \
		Direction.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		ui_OpenButton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OpenButton.o OpenButton.cpp

Passenger.o: Passenger.cpp Passenger.h \
		SimulationComponent.h \
		PassengerState.h \
		Button.h \
		ui_Passenger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Passenger.o Passenger.cpp

PassengerSetting.o: PassengerSetting.cpp PassengerSetting.h \
		Direction.h \
		ui_PassengerSetting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PassengerSetting.o PassengerSetting.cpp

Simulation.o: Simulation.cpp Simulation.h \
		ElevatorSetting.h \
		PassengerSetting.h \
		Direction.h \
		BuildingSetting.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		SimulationComponent.h \
		Display.h \
		Speaker.h \
		OpenButton.h \
		Button.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		Passenger.h \
		PassengerState.h \
		Floor.h \
		FloorButton.h \
		SimulationManager.h \
		ui_Simulation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Simulation.o Simulation.cpp

Speaker.o: Speaker.cpp Speaker.h \
		SimulationComponent.h \
		ui_Speaker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Speaker.o Speaker.cpp

main.o: main.cpp MainWindow.h \
		ElevatorSetting.h \
		PassengerSetting.h \
		Direction.h \
		BuildingSetting.h \
		Simulation.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		SimulationComponent.h \
		Display.h \
		Speaker.h \
		OpenButton.h \
		Button.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		Passenger.h \
		PassengerState.h \
		Floor.h \
		FloorButton.h \
		SimulationManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ElevatorControl.o: ElevatorControl.cpp ElevatorControl.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		SimulationComponent.h \
		Display.h \
		Speaker.h \
		Direction.h \
		OpenButton.h \
		Button.h \
		CloseButton.h \
		HelpButton.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		Random.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ElevatorControl.o ElevatorControl.cpp

NCStrategy.o: NCStrategy.cpp NCStrategy.h \
		AllocationStrategy.h \
		FloorRequest.h \
		Direction.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		SimulationComponent.h \
		Display.h \
		Speaker.h \
		OpenButton.h \
		Button.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NCStrategy.o NCStrategy.cpp

FloorRequest.o: FloorRequest.cpp FloorRequest.h \
		Direction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FloorRequest.o FloorRequest.cpp

SimulationManager.o: SimulationManager.cpp SimulationManager.h \
		Elevator.h \
		ElevatorState.h \
		Door.h \
		DoorState.h \
		SimulationComponent.h \
		Display.h \
		Speaker.h \
		Direction.h \
		OpenButton.h \
		Button.h \
		CloseButton.h \
		HelpButton.h \
		ElevatorControl.h \
		AllocationStrategy.h \
		FloorRequest.h \
		NCStrategy.h \
		Passenger.h \
		PassengerState.h \
		Floor.h \
		FloorButton.h \
		ElevatorSetting.h \
		PassengerSetting.h \
		BuildingSetting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SimulationManager.o SimulationManager.cpp

moc_CloseButton.o: moc_CloseButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CloseButton.o moc_CloseButton.cpp

moc_Display.o: moc_Display.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Display.o moc_Display.cpp

moc_Door.o: moc_Door.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Door.o moc_Door.cpp

moc_Elevator.o: moc_Elevator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Elevator.o moc_Elevator.cpp

moc_ElevatorSetting.o: moc_ElevatorSetting.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ElevatorSetting.o moc_ElevatorSetting.cpp

moc_Floor.o: moc_Floor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Floor.o moc_Floor.cpp

moc_FloorButton.o: moc_FloorButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FloorButton.o moc_FloorButton.cpp

moc_HelpButton.o: moc_HelpButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HelpButton.o moc_HelpButton.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_OpenButton.o: moc_OpenButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_OpenButton.o moc_OpenButton.cpp

moc_Passenger.o: moc_Passenger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Passenger.o moc_Passenger.cpp

moc_PassengerSetting.o: moc_PassengerSetting.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PassengerSetting.o moc_PassengerSetting.cpp

moc_Simulation.o: moc_Simulation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Simulation.o moc_Simulation.cpp

moc_SimulationComponent.o: moc_SimulationComponent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SimulationComponent.o moc_SimulationComponent.cpp

moc_Button.o: moc_Button.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Button.o moc_Button.cpp

moc_Speaker.o: moc_Speaker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Speaker.o moc_Speaker.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ElevatorSimulator/bin || mkdir -p $(INSTALL_ROOT)/opt/ElevatorSimulator/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ElevatorSimulator/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ElevatorSimulator/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ElevatorSimulator/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

